const QUESTIONS = [
  { id: 1, a: "manger des excréments sans boire d'eau", b: "boire du liquide amniotique à la paille", pctA: 55 },
  { id: 2, a: "te brûler le bout de la langue avec des ciseaux", b: "manger un oiseau mort sans boire d'eau", pctA: 18 },
  { id: 3, a: "t'arracher le nez avec un coupe-papier", b: "te couper un ongle sans anesthésie", pctA: 43 },
  { id: 4, a: "embrasser avec la langue l'anus d'un chien jusqu'à ce que ce soit propre", b: "te faire sodomiser par une chèvre au supermarché", pctA: 41 },
  { id: 5, a: "te brûler le clitoris lentement", b: "te chier dessus sur la tête de ton enfant et ne pas pouvoir te changer", pctA: 33 },
  { id: 6, a: "mâcher un tampon usagé devant ton boss", b: "lécher les pieds d'un lépreux avec passion", pctA: 69 },
  { id: 7, a: "te percer le clitoris sans anesthésie", b: "masturber ton boss dans une église", pctA: 27 },
  { id: 8, a: "manger un fœtus de vache comme un sandwich", b: "plonger nu dans du fumier chaque week-end", pctA: 22 },
  { id: 9, a: "lécher le trottoir de Paris jusqu'à ce que ce soit propre", b: "avaler du crachat à la paille", pctA: 21 },
  { id: 10, a: "avoir des pénis à la place des doigts chaque matin", b: "manger un placenta sans boire d'eau", pctA: 71 },
  { id: 11, a: "te pisser dessus à l'église en pleurant", b: "vomir à l'église en hurlant", pctA: 48 },
  { id: 12, a: "sucer une plaie purulente pendant 5 minutes", b: "te couper le tympan avec une pince rouillée", pctA: 55 },
  { id: 13, a: "siroter du liquide amniotique chaque soir", b: "croquer dans un préservatif plein sans boire d'eau", pctA: 70 },
  { id: 14, a: "t'arracher le clitoris avec des ciseaux", b: "te rouler dans du purin pendant 1 heure", pctA: 19 },
  { id: 15, a: "plonger nu dans des déchets toxiques pendant 1 heure", b: "siroter du jus de poubelle chaque matin", pctA: 72 },
  { id: 16, a: "avoir un 3ème bras dans le dos quand tu es excité", b: "masturber un vieillard de 90 ans devant tes parents", pctA: 44 },
  { id: 17, a: "t'arracher les testicules avec des ciseaux", b: "t'enfoncer une aiguille dans le tympan sans anesthésie", pctA: 59 },
  { id: 18, a: "mâcher un cafard géant devant ton boss", b: "mâcher une limace vivante sans boire d'eau", pctA: 68 },
  { id: 19, a: "sucer un vieillard de 90 ans au supermarché", b: "t'arracher un ongle avec un coupe-papier", pctA: 60 },
  { id: 20, a: "croquer dans un préservatif plein comme un sandwich", b: "te rouler dans une baignoire de vomi avec des plaies ouvertes", pctA: 55 },
  { id: 21, a: "te baigner dans une piscine de pisse avec des plaies ouvertes", b: "sucer l'anus d'un chien pendant 5 minutes", pctA: 82 },
  { id: 22, a: "déguster des asticots sans boire d'eau", b: "uriner du tabasco chaque matin", pctA: 48 },
  { id: 23, a: "te rouler dans une piscine de pisse avec des plaies ouvertes", b: "manger un préservatif plein sans boire d'eau", pctA: 53 },
  { id: 24, a: "sucer un gorille en rut sur la place publique", b: "te brûler les lèvres sans anesthésie", pctA: 42 },
  { id: 25, a: "embrasser avec la langue les pieds d'un lépreux en filmant", b: "plonger nu dans des viscères chaque week-end", pctA: 51 },
  { id: 26, a: "avaler du liquide amniotique au réveil", b: "te gargariser avec de la morve liquide chaque matin", pctA: 30 },
  { id: 27, a: "te rouler dans du sang animal chaque week-end", b: "siroter du crachat à la paille", pctA: 16 },
  { id: 28, a: "déguster de la viande avariée devant ton boss", b: "péter bruyamment au premier rendez-vous et faire comme si de rien n'était", pctA: 26 },
  { id: 29, a: "manger un œil de chèvre devant ton boss", b: "te faire doigter par un sans-abri édenté au supermarché", pctA: 26 },
  { id: 30, a: "avaler un verre de sueur à la paille", b: "éjaculer à ton mariage en pleurant", pctA: 48 },
  { id: 31, a: "déguster de la viande avariée comme un sandwich", b: "croquer dans de la cervelle crue devant ton boss", pctA: 44 },
  { id: 32, a: "déguster un oiseau mort sans boire d'eau", b: "lécher une barre de métro jusqu'à ce que ce soit propre", pctA: 18 },
  { id: 33, a: "te rouler dans des déchets toxiques avec des plaies ouvertes", b: "avaler un verre de sueur au réveil", pctA: 30 },
  { id: 34, a: "te faire doigter par ton prof de lycée en direct sur Twitch", b: "sucer un gorille en rut en direct sur Twitch", pctA: 18 },
  { id: 35, a: "uriner des lames de rasoir quand tu es excité", b: "lécher les aisselles non rasées d'un SDF jusqu'à ce que ce soit propre", pctA: 79 },
  { id: 36, a: "déguster un placenta au petit déjeuner", b: "te chier dessus à ton mariage et ne pas pouvoir te changer", pctA: 82 },
  { id: 37, a: "éjaculer dans le métro bondé et faire comme si de rien n'était", b: "sucer le vagin d'une vache jusqu'à ce que ce soit propre", pctA: 28 },
  { id: 38, a: "avoir des testicules au menton chaque matin", b: "mâcher de la viande avariée avec les doigts", pctA: 41 },
  { id: 39, a: "t'enfoncer une aiguille dans un œil avec des ciseaux", b: "manger des ongles d'orteils coupés devant ton boss", pctA: 72 },
  { id: 40, a: "boire de la morve liquide à la paille", b: "embrasser avec la langue l'anus d'un chien en public", pctA: 79 },
  { id: 41, a: "lécher le trottoir de Paris en filmant", b: "sucer le sol des chiottes publiques en filmant", pctA: 41 },
  { id: 42, a: "sucer les aisselles non rasées d'un SDF avec passion", b: "te baigner dans du purin avec des plaies ouvertes", pctA: 83 },
  { id: 43, a: "te baigner dans des déchets toxiques chaque week-end", b: "te faire doigter par un nain de jardin sur la place publique", pctA: 19 },
  { id: 44, a: "sucer le trottoir de Paris pendant 5 minutes", b: "manger un préservatif plein au petit déjeuner", pctA: 85 },
  { id: 45, a: "siroter du liquide amniotique à la paille", b: "te faire sodomiser par le cadavre de ton pire ennemi en direct sur Twitch", pctA: 71 },
  { id: 46, a: "masturber une personne qui a la lèpre au supermarché", b: "éjaculer au premier rendez-vous en pleurant", pctA: 72 },
  { id: 47, a: "te faire doigter par un vieillard de 90 ans au supermarché", b: "te percer le tympan avec un coupe-papier", pctA: 65 },
  { id: 48, a: "sucer le cadavre de ton pire ennemi sur la place publique", b: "te gargariser avec de la diarrhée liquide chaque matin", pctA: 41 },
  { id: 49, a: "avaler de la cyprine rance à la paille", b: "te brûler un œil lentement", pctA: 56 },
  { id: 50, a: "te couper les lèvres avec une pince rouillée", b: "sucer un vieillard de 90 ans devant tes parents", pctA: 65 },
  { id: 51, a: "mâcher des crottes de nez au petit déjeuner", b: "mâcher une limace vivante comme un sandwich", pctA: 42 },
  { id: 52, a: "avaler du sang de porc au réveil", b: "avaler du vomi de chien au réveil", pctA: 41 },
  { id: 53, a: "sucer un nain de jardin au supermarché", b: "avoir des seins sur les genoux pour le reste de ta vie", pctA: 19 },
  { id: 54, a: "boire du liquide amniotique au réveil", b: "te pisser dessus sur la tête de ton enfant et ne pas pouvoir te changer", pctA: 47 },
  { id: 55, a: "éjaculer sur la tête de ton enfant en hurlant", b: "te couper une dent avec des ciseaux", pctA: 20 },
  { id: 56, a: "mâcher des ongles d'orteils coupés devant ton boss", b: "coucher avec ton boss sur la place publique", pctA: 75 },
  { id: 57, a: "avoir des testicules au menton à chaque fois que tu mens", b: "te faire sodomiser par une chèvre dans une église", pctA: 49 },
  { id: 58, a: "te gargariser avec du sang de porc chaque soir", b: "avoir des seins sur les genoux chaque matin", pctA: 50 },
  { id: 59, a: "sucer le meilleur ami de ton père dans une église", b: "te percer les lèvres avec un coupe-papier", pctA: 57 },
  { id: 60, a: "mâcher un cafard géant sans boire d'eau", b: "te faire sodomiser par une personne qui a la lèpre dans une église", pctA: 59 },
  { id: 61, a: "te faire sodomiser par un nain de jardin devant tes parents", b: "manger des excréments comme un sandwich", pctA: 73 },
  { id: 62, a: "t'enfoncer une aiguille dans le clitoris avec des ciseaux", b: "croquer dans des asticots sans boire d'eau", pctA: 29 },
  { id: 63, a: "te faire doigter par une personne qui a la lèpre dans une église", b: "avaler du vomi de chien chaque soir", pctA: 31 },
  { id: 64, a: "éjaculer dans le métro bondé en hurlant", b: "masturber un gorille en rut en direct sur Twitch", pctA: 50 },
  { id: 65, a: "sucer le trottoir de Paris en filmant", b: "te percer un œil sans anesthésie", pctA: 52 },
  { id: 66, a: "te baigner dans des déchets toxiques pendant 1 heure", b: "te gargariser avec du sang de porc au réveil", pctA: 82 },
  { id: 67, a: "te brûler un œil sans anesthésie", b: "avaler un verre de sueur chaque soir", pctA: 59 },
  { id: 68, a: "masturber ton prof de lycée sur la place publique", b: "masturber le cadavre de ton pire ennemi devant tes parents", pctA: 56 },
  { id: 69, a: "avaler du vomi de chien chaque matin", b: "sucer un gorille en rut dans une église", pctA: 15 },
  { id: 70, a: "te couper un ongle avec des ciseaux", b: "t'arracher le clitoris sans anesthésie", pctA: 34 },
  { id: 71, a: "croquer dans un œil de chèvre comme un sandwich", b: "plonger nu dans de l'eau d'égout sans pouvoir te doucher après", pctA: 57 },
  { id: 72, a: "déguster une limace vivante avec les doigts", b: "croquer dans une limace vivante avec les doigts", pctA: 19 },
  { id: 73, a: "vomir aux funérailles de ta mère et faire comme si de rien n'était", b: "avaler de la diarrhée liquide chaque soir", pctA: 31 },
  { id: 74, a: "t'enfoncer une aiguille dans le clitoris avec un coupe-papier", b: "sucer les pieds d'un lépreux pendant 5 minutes", pctA: 73 },
  { id: 75, a: "te percer une dent lentement", b: "masturber le cadavre de ton pire ennemi sur la place publique", pctA: 42 },
  { id: 76, a: "siroter du pus infecté au réveil", b: "te brûler le tympan lentement", pctA: 18 },
  { id: 77, a: "embrasser avec la langue les aisselles d'un clochard avec passion", b: "coucher avec le cadavre de ton pire ennemi en direct sur Twitch", pctA: 69 },
  { id: 78, a: "avaler un bol de diarrhée chaque soir", b: "sucer un vieillard de 90 ans sur la place publique", pctA: 29 },
  { id: 79, a: "boire un bol de diarrhée chaque soir", b: "boire de la cyprine rance à la paille", pctA: 74 },
  { id: 80, a: "manger un rat mort devant ton boss", b: "vomir au premier rendez-vous et faire comme si de rien n'était", pctA: 60 },
  { id: 81, a: "mâcher un préservatif plein au petit déjeuner", b: "siroter du liquide amniotique chaque matin", pctA: 78 },
  { id: 82, a: "vomir à ton mariage et faire comme si de rien n'était", b: "sucer un ours en peluche géant sur la place publique", pctA: 55 },
  { id: 83, a: "avaler de la diarrhée liquide au réveil", b: "te percer le bout de la langue lentement", pctA: 40 },
  { id: 84, a: "mâcher des pellicules devant ton boss", b: "te chier dessus sur la tête de ton enfant et faire comme si de rien n'était", pctA: 24 },
  { id: 85, a: "coucher avec une personne qui a la lèpre sur la place publique", b: "mâcher un œil de chèvre au petit déjeuner", pctA: 30 },
  { id: 86, a: "masturber un vieillard de 90 ans en direct sur Twitch", b: "mâcher un rat mort devant ton boss", pctA: 29 },
  { id: 87, a: "te faire sodomiser par une personne qui a la lèpre devant tes parents", b: "avaler de la diarrhée liquide devant ta famille", pctA: 29 },
  { id: 88, a: "lécher l'anus d'un chien en public", b: "manger un placenta au petit déjeuner", pctA: 76 },
  { id: 89, a: "mâcher des asticots comme un sandwich", b: "déguster des ongles d'orteils coupés avec les doigts", pctA: 79 },
  { id: 90, a: "boire un verre de sueur à la paille", b: "te brûler un œil avec une pince rouillée", pctA: 67 },
  { id: 91, a: "t'enfoncer une aiguille dans le nez avec des ciseaux", b: "lécher le trottoir de Paris pendant 5 minutes", pctA: 43 },
  { id: 92, a: "te brûler le tympan sans anesthésie", b: "siroter de la cyprine rance chaque soir", pctA: 58 },
  { id: 93, a: "boire de la diarrhée liquide chaque matin", b: "déguster un cafard géant au petit déjeuner", pctA: 77 },
  { id: 94, a: "boire du jus de poubelle au réveil", b: "t'enfoncer une aiguille dans le nez avec un coupe-papier", pctA: 31 },
  { id: 95, a: "boire du sang de porc devant ta famille", b: "avaler du pus infecté chaque matin", pctA: 47 },
  { id: 96, a: "transpirer du beurre fondu quand tu es excité", b: "te chier dessus au premier rendez-vous et faire comme si de rien n'était", pctA: 85 },
  { id: 97, a: "te gargariser avec de l'eau des toilettes au réveil", b: "croquer dans des vers de terre avec les doigts", pctA: 70 },
  { id: 98, a: "sucer les aisselles d'un clochard jusqu'à ce que ce soit propre", b: "avaler du crachat au réveil", pctA: 83 },
  { id: 99, a: "embrasser avec la langue les aisselles d'un clochard en public", b: "masturber ton cousin germain au supermarché", pctA: 18 },
  { id: 100, a: "te baigner dans une baignoire de vomi avec des plaies ouvertes", b: "lécher la cuvette des toilettes avec passion", pctA: 52 },
  { id: 101, a: "croquer dans un fœtus de vache devant ton boss", b: "te rouler dans du fumier pendant 1 heure", pctA: 58 },
  { id: 102, a: "manger des vers de terre devant ton boss", b: "sucer ton prof de lycée dans une église", pctA: 44 },
  { id: 103, a: "plonger nu dans du goudron bouillant pendant 1 heure", b: "siroter de la cyprine rance chaque matin", pctA: 50 },
  { id: 104, a: "embrasser avec la langue un furoncle éclaté en public", b: "te faire sodomiser par le cadavre de ton pire ennemi devant tes parents", pctA: 18 },
  { id: 105, a: "t'arracher l'urètre avec des ciseaux", b: "te rouler dans du sang animal sans pouvoir te doucher après", pctA: 50 },
  { id: 106, a: "manger un œil de chèvre sans boire d'eau", b: "manger des excréments au petit déjeuner", pctA: 48 },
  { id: 107, a: "éternuer de l'acide à chaque fois que tu mens", b: "te chier dessus au premier rendez-vous en pleurant", pctA: 69 },
  { id: 108, a: "te faire doigter par une chèvre sur la place publique", b: "sucer les testicules d'un bouc avec passion", pctA: 40 },
  { id: 109, a: "mâcher un œil de chèvre sans boire d'eau", b: "boire du vomi de chien au réveil", pctA: 68 },
  { id: 110, a: "vomir dans le métro bondé et ne pas pouvoir te changer", b: "masturber un nain de jardin sur la place publique", pctA: 83 },
  { id: 111, a: "t'enfoncer une aiguille dans l'urètre avec un coupe-papier", b: "masturber le cadavre de ton pire ennemi en direct sur Twitch", pctA: 26 },
  { id: 112, a: "déféquer des boules de pétanque à chaque fois que tu mens", b: "croquer dans un placenta sans boire d'eau", pctA: 40 },
  { id: 113, a: "péter bruyamment au premier rendez-vous en pleurant", b: "siroter du smegma chaque matin", pctA: 83 },
  { id: 114, a: "manger un oiseau mort avec les doigts", b: "déguster de la cervelle crue comme un sandwich", pctA: 42 },
  { id: 115, a: "masturber le meilleur ami de ton père en direct sur Twitch", b: "plonger nu dans de la bave pendant 1 heure", pctA: 31 },
  { id: 116, a: "plonger nu dans des déchets toxiques sans pouvoir te doucher après", b: "lécher les pieds d'un lépreux jusqu'à ce que ce soit propre", pctA: 29 },
  { id: 117, a: "te percer le bout de la langue avec un coupe-papier", b: "manger de la cervelle crue au petit déjeuner", pctA: 55 },
  { id: 118, a: "siroter du vomi de chien chaque matin", b: "lécher le trottoir de Paris en public", pctA: 70 },
  { id: 119, a: "t'enfoncer une aiguille dans un ongle avec des ciseaux", b: "croquer dans un tampon usagé au petit déjeuner", pctA: 69 },
  { id: 120, a: "te couper les testicules avec un coupe-papier", b: "te faire sodomiser par un ours en peluche géant au supermarché", pctA: 22 },
  { id: 121, a: "croquer dans des vers de terre au petit déjeuner", b: "masturber ton prof de lycée au supermarché", pctA: 34 },
  { id: 122, a: "sucer une barre de métro en filmant", b: "sucer le groin d'un porc jusqu'à ce que ce soit propre", pctA: 67 },
  { id: 123, a: "sucer la cuvette des toilettes en public", b: "déguster de la viande avariée au petit déjeuner", pctA: 32 },
  { id: 124, a: "croquer dans des excréments comme un sandwich", b: "déguster un oiseau mort au petit déjeuner", pctA: 49 },
  { id: 125, a: "te faire sodomiser par une chèvre sur la place publique", b: "masturber un extraterrestre tentaculaire sur la place publique", pctA: 15 },
  { id: 126, a: "mâcher un cafard géant au petit déjeuner", b: "lécher l'anus d'un chien jusqu'à ce que ce soit propre", pctA: 17 },
  { id: 127, a: "siroter du crachat devant ta famille", b: "manger un tampon usagé sans boire d'eau", pctA: 19 },
  { id: 128, a: "te percer le tympan avec une pince rouillée", b: "te couper un œil avec un coupe-papier", pctA: 45 },
  { id: 129, a: "embrasser avec la langue les pieds d'un lépreux jusqu'à ce que ce soit propre", b: "péter bruyamment à ton mariage en pleurant", pctA: 28 },
  { id: 130, a: "avaler du smegma au réveil", b: "boire un smoothie au cérumen chaque matin", pctA: 65 },
  { id: 131, a: "te chier dessus à l'église en pleurant", b: "manger de la cervelle crue sans boire d'eau", pctA: 18 },
  { id: 132, a: "boire du jus de poubelle chaque soir", b: "plonger nu dans une baignoire de vomi avec des plaies ouvertes", pctA: 41 },
  { id: 133, a: "masturber un ours en peluche géant en direct sur Twitch", b: "siroter un smoothie au cérumen devant ta famille", pctA: 82 },
  { id: 134, a: "te gargariser avec de la morve liquide à la paille", b: "uriner des lames de rasoir pour le reste de ta vie", pctA: 32 },
  { id: 135, a: "te pisser dessus à ton mariage et ne pas pouvoir te changer", b: "te chier dessus aux funérailles de ta mère et faire comme si de rien n'était", pctA: 46 },
  { id: 136, a: "manger de la viande avariée sans boire d'eau", b: "coucher avec un extraterrestre tentaculaire dans une église", pctA: 72 },
  { id: 137, a: "avaler du jus de poubelle chaque soir", b: "coucher avec ton cousin germain devant tes parents", pctA: 29 },
  { id: 138, a: "avaler un bol de diarrhée chaque matin", b: "avaler de la morve liquide chaque matin", pctA: 20 },
  { id: 139, a: "coucher avec le cadavre de ton pire ennemi au supermarché", b: "croquer dans un œil de chèvre avec les doigts", pctA: 53 },
  { id: 140, a: "mâcher des excréments sans boire d'eau", b: "te faire doigter par un extraterrestre tentaculaire sur la place publique", pctA: 24 },
  { id: 141, a: "te faire doigter par ton cousin germain sur la place publique", b: "siroter de l'eau des toilettes chaque soir", pctA: 47 },
  { id: 142, a: "plonger nu dans des viscères pendant 1 heure", b: "lécher un furoncle éclaté avec passion", pctA: 46 },
  { id: 143, a: "te gargariser avec du smegma à la paille", b: "siroter du crachat chaque matin", pctA: 45 },
  { id: 144, a: "avaler du jus de poubelle devant ta famille", b: "siroter du smegma devant ta famille", pctA: 40 },
  { id: 145, a: "avaler du jus de poubelle à la paille", b: "t'enfoncer une aiguille dans le clitoris lentement", pctA: 34 },
  { id: 146, a: "croquer dans des pellicules devant ton boss", b: "te faire doigter par le cadavre de ton pire ennemi en direct sur Twitch", pctA: 80 },
  { id: 147, a: "croquer dans des asticots comme un sandwich", b: "t'arracher le tympan sans anesthésie", pctA: 40 },
  { id: 148, a: "te pisser dessus à l'église et ne pas pouvoir te changer", b: "te baigner dans du purin pendant 1 heure", pctA: 25 },
  { id: 149, a: "siroter de la morve liquide chaque matin", b: "te couper le bout de la langue avec un coupe-papier", pctA: 48 },
  { id: 150, a: "boire de l'eau des toilettes chaque soir", b: "te percer le bout de la langue avec une pince rouillée", pctA: 42 },
  { id: 151, a: "péter bruyamment au premier rendez-vous en hurlant", b: "te brûler le bout de la langue sans anesthésie", pctA: 16 },
  { id: 152, a: "mâcher un fœtus de vache au petit déjeuner", b: "boire du pus infecté chaque matin", pctA: 57 },
  { id: 153, a: "masturber une chèvre au supermarché", b: "croquer dans un oiseau mort comme un sandwich", pctA: 40 },
  { id: 154, a: "t'enfoncer une aiguille dans l'urètre avec une pince rouillée", b: "mâcher de la cervelle crue devant ton boss", pctA: 69 },
  { id: 155, a: "te couper l'urètre lentement", b: "plonger nu dans des viscères avec des plaies ouvertes", pctA: 49 },
  { id: 156, a: "masturber un sans-abri édenté en direct sur Twitch", b: "embrasser avec la langue le vagin d'une vache en filmant", pctA: 60 },
  { id: 157, a: "embrasser avec la langue les pieds d'un lépreux avec passion", b: "manger un fœtus de vache avec les doigts", pctA: 43 },
  { id: 158, a: "boire un verre de sueur devant ta famille", b: "te faire sodomiser par un sans-abri édenté sur la place publique", pctA: 35 },
  { id: 159, a: "sucer le meilleur ami de ton père sur la place publique", b: "manger des ongles d'orteils coupés comme un sandwich", pctA: 70 },
  { id: 160, a: "sucer la cuvette des toilettes pendant 5 minutes", b: "te chier dessus pendant un entretien d'embauche en pleurant", pctA: 44 },
  { id: 161, a: "t'enfoncer une aiguille dans un œil avec une pince rouillée", b: "masturber un nain de jardin en direct sur Twitch", pctA: 21 },
  { id: 162, a: "manger des ongles d'orteils coupés au petit déjeuner", b: "masturber ton prof de lycée devant tes parents", pctA: 21 },
  { id: 163, a: "boire du vomi de chien chaque matin", b: "sucer ton cousin germain au supermarché", pctA: 56 },
  { id: 164, a: "sucer les testicules d'un bouc en public", b: "péter bruyamment dans le métro bondé et faire comme si de rien n'était", pctA: 67 },
  { id: 165, a: "manger des pellicules comme un sandwich", b: "péter bruyamment sur la tête de ton enfant et faire comme si de rien n'était", pctA: 23 },
  { id: 166, a: "déguster des crottes de nez avec les doigts", b: "te gargariser avec du pus infecté à la paille", pctA: 56 },
  { id: 167, a: "mâcher des crottes de nez comme un sandwich", b: "masturber ton boss au supermarché", pctA: 18 },
  { id: 168, a: "t'arracher les testicules avec un coupe-papier", b: "siroter du smegma à la paille", pctA: 56 },
  { id: 169, a: "manger des crottes de nez sans boire d'eau", b: "manger un oiseau mort comme un sandwich", pctA: 73 },
  { id: 170, a: "t'arracher l'urètre avec un coupe-papier", b: "coucher avec un sans-abri édenté devant tes parents", pctA: 45 },
  { id: 171, a: "plonger nu dans une piscine de pisse pendant 1 heure", b: "te percer l'urètre avec une pince rouillée", pctA: 21 },
  { id: 172, a: "boire un verre de sueur chaque soir", b: "déguster des excréments au petit déjeuner", pctA: 84 },
  { id: 173, a: "te faire doigter par un vieillard de 90 ans sur la place publique", b: "te faire doigter par un nain de jardin au supermarché", pctA: 67 },
  { id: 174, a: "manger des asticots avec les doigts", b: "mâcher un placenta sans boire d'eau", pctA: 55 },
  { id: 175, a: "te couper le nez lentement", b: "croquer dans des ongles d'orteils coupés sans boire d'eau", pctA: 44 },
  { id: 176, a: "croquer dans un placenta au petit déjeuner", b: "siroter du smegma chaque soir", pctA: 40 },
  { id: 177, a: "lécher un furoncle éclaté en public", b: "te percer le tympan avec des ciseaux", pctA: 18 },
  { id: 178, a: "déguster un tampon usagé au petit déjeuner", b: "siroter un litre de pisse tiède à la paille", pctA: 26 },
  { id: 179, a: "vomir sur la tête de ton enfant en hurlant", b: "te faire doigter par le meilleur ami de ton père en direct sur Twitch", pctA: 30 },
  { id: 180, a: "péter bruyamment à l'église et ne pas pouvoir te changer", b: "avaler de la diarrhée liquide à la paille", pctA: 25 },
  { id: 181, a: "lécher une barre de métro pendant 5 minutes", b: "déguster un placenta comme un sandwich", pctA: 79 },
  { id: 182, a: "sucer ton cousin germain en direct sur Twitch", b: "coucher avec un ours en peluche géant au supermarché", pctA: 32 },
  { id: 183, a: "te rouler dans des viscères chaque week-end", b: "te chier dessus dans le métro bondé et ne pas pouvoir te changer", pctA: 44 },
  { id: 184, a: "te chier dessus en serrant la main du président en hurlant", b: "mâcher des pellicules comme un sandwich", pctA: 73 },
  { id: 185, a: "te baigner dans du goudron bouillant chaque week-end", b: "te gargariser avec du jus de poubelle chaque soir", pctA: 75 },
  { id: 186, a: "manger un placenta avec les doigts", b: "te couper un œil lentement", pctA: 18 },
  { id: 187, a: "embrasser avec la langue les testicules d'un bouc pendant 5 minutes", b: "embrasser avec la langue le vagin d'une vache en public", pctA: 73 },
  { id: 188, a: "avaler du smegma à la paille", b: "mâcher un fœtus de vache avec les doigts", pctA: 74 },
  { id: 189, a: "avaler un litre de pisse tiède au réveil", b: "lécher le sol des chiottes publiques jusqu'à ce que ce soit propre", pctA: 59 },
  { id: 190, a: "te faire sodomiser par un nain de jardin au supermarché", b: "déguster un placenta sans boire d'eau", pctA: 58 },
  { id: 191, a: "te couper le clitoris avec une pince rouillée", b: "te gargariser avec du liquide amniotique devant ta famille", pctA: 48 },
  { id: 192, a: "manger de la viande avariée devant ton boss", b: "mâcher un placenta devant ton boss", pctA: 30 },
  { id: 193, a: "embrasser avec la langue la cuvette des toilettes en public", b: "te rouler dans une piscine de pisse sans pouvoir te doucher après", pctA: 17 },
  { id: 194, a: "te gargariser avec un smoothie au cérumen devant ta famille", b: "mâcher de la viande avariée sans boire d'eau", pctA: 50 },
  { id: 195, a: "sucer une barre de métro en public", b: "déguster un préservatif plein au petit déjeuner", pctA: 42 },
  { id: 196, a: "manger de la viande avariée comme un sandwich", b: "te percer le mamelon avec une pince rouillée", pctA: 32 },
  { id: 197, a: "embrasser avec la langue les aisselles d'un clochard pendant 5 minutes", b: "vomir au premier rendez-vous et ne pas pouvoir te changer", pctA: 43 },
  { id: 198, a: "coucher avec ton cousin germain en direct sur Twitch", b: "te rouler dans du sperme d'animal sans pouvoir te doucher après", pctA: 24 },
  { id: 199, a: "pondre un œuf par l'anus à chaque fois que tu mens", b: "déguster des asticots au petit déjeuner", pctA: 21 },
  { id: 200, a: "masturber le meilleur ami de ton père dans une église", b: "te faire doigter par un gorille en rut en direct sur Twitch", pctA: 74 },
  { id: 201, a: "masturber ton cousin germain en direct sur Twitch", b: "te baigner dans du fumier pendant 1 heure", pctA: 29 },
  { id: 202, a: "pondre un œuf par l'anus chaque matin", b: "mâcher un oiseau mort sans boire d'eau", pctA: 28 },
  { id: 203, a: "t'arracher le mamelon avec une pince rouillée", b: "mâcher un placenta avec les doigts", pctA: 85 },
  { id: 204, a: "te baigner dans du fumier chaque week-end", b: "manger un cafard géant avec les doigts", pctA: 30 },
  { id: 205, a: "te faire sodomiser par un sans-abri édenté en direct sur Twitch", b: "te pisser dessus pendant un entretien d'embauche et faire comme si de rien n'était", pctA: 28 },
  { id: 206, a: "t'enfoncer une aiguille dans le bout de la langue sans anesthésie", b: "déguster un cafard géant devant ton boss", pctA: 51 },
  { id: 207, a: "déguster un fœtus de vache au petit déjeuner", b: "siroter du sang de porc au réveil", pctA: 73 },
  { id: 208, a: "te gargariser avec un litre de pisse tiède à la paille", b: "te gargariser avec un bol de diarrhée à la paille", pctA: 69 },
  { id: 209, a: "croquer dans un fœtus de vache comme un sandwich", b: "déguster des crottes de nez sans boire d'eau", pctA: 84 },
  { id: 210, a: "te faire sodomiser par ton prof de lycée devant tes parents", b: "sucer l'anus d'un chien avec passion", pctA: 26 },
  { id: 211, a: "coucher avec le meilleur ami de ton père dans une église", b: "te percer le clitoris lentement", pctA: 15 },
  { id: 212, a: "siroter un litre de pisse tiède chaque matin", b: "t'arracher un ongle avec des ciseaux", pctA: 58 },
  { id: 213, a: "plonger nu dans du sang animal chaque week-end", b: "siroter du sang de porc chaque matin", pctA: 85 },
  { id: 214, a: "te faire sodomiser par un gorille en rut sur la place publique", b: "coucher avec un vieillard de 90 ans dans une église", pctA: 66 },
  { id: 215, a: "te baigner dans du goudron bouillant pendant 1 heure", b: "embrasser avec la langue une barre de métro en filmant", pctA: 53 },
  { id: 216, a: "déguster de la cervelle crue au petit déjeuner", b: "embrasser avec la langue les testicules d'un bouc en public", pctA: 60 },
  { id: 217, a: "avaler du pus infecté devant ta famille", b: "péter bruyamment sur la tête de ton enfant en hurlant", pctA: 51 },
  { id: 218, a: "te gargariser avec du crachat chaque soir", b: "te chier dessus dans le métro bondé en hurlant", pctA: 29 },
  { id: 219, a: "boire de l'eau des toilettes au réveil", b: "déguster un préservatif plein avec les doigts", pctA: 78 },
  { id: 220, a: "t'arracher le tympan lentement", b: "te gargariser avec du crachat au réveil", pctA: 71 },
  { id: 221, a: "cracher des dents quand tu es excité", b: "te couper le nez sans anesthésie", pctA: 34 },
  { id: 222, a: "embrasser avec la langue un furoncle éclaté jusqu'à ce que ce soit propre", b: "déguster de la viande avariée avec les doigts", pctA: 44 },
  { id: 223, a: "te couper le bout de la langue avec une pince rouillée", b: "avaler un smoothie au cérumen chaque soir", pctA: 58 },
  { id: 224, a: "croquer dans des pellicules au petit déjeuner", b: "t'arracher le bout de la langue avec un coupe-papier", pctA: 33 },
  { id: 225, a: "éternuer de l'acide pour le reste de ta vie", b: "masturber un sans-abri édenté devant tes parents", pctA: 19 },
  { id: 226, a: "sucer un sans-abri édenté au supermarché", b: "avaler un litre de pisse tiède chaque matin", pctA: 33 },
  { id: 227, a: "te rouler dans des déchets toxiques sans pouvoir te doucher après", b: "sucer le groin d'un porc en filmant", pctA: 59 },
  { id: 228, a: "avaler de la cyprine rance chaque matin", b: "mâcher un rat mort au petit déjeuner", pctA: 58 },
  { id: 229, a: "te faire doigter par un sans-abri édenté devant tes parents", b: "sucer le groin d'un porc avec passion", pctA: 28 },
  { id: 230, a: "te couper le clitoris lentement", b: "te brûler l'urètre lentement", pctA: 18 },
  { id: 231, a: "lécher les pieds d'un lépreux en filmant", b: "sucer le cadavre de ton pire ennemi devant tes parents", pctA: 22 },
  { id: 232, a: "coucher avec un gorille en rut devant tes parents", b: "t'arracher un œil lentement", pctA: 45 },
  { id: 233, a: "sucer l'anus d'un chien en filmant", b: "croquer dans un rat mort au petit déjeuner", pctA: 15 },
  { id: 234, a: "boire de la diarrhée liquide chaque soir", b: "manger des asticots devant ton boss", pctA: 55 },
  { id: 235, a: "manger un fœtus de vache au petit déjeuner", b: "boire de la cyprine rance chaque matin", pctA: 20 },
  { id: 236, a: "te gargariser avec de la cyprine rance chaque matin", b: "plonger nu dans du purin chaque week-end", pctA: 27 },
  { id: 237, a: "sucer un furoncle éclaté jusqu'à ce que ce soit propre", b: "déguster un placenta avec les doigts", pctA: 68 },
  { id: 238, a: "sucer les testicules d'un bouc pendant 5 minutes", b: "déguster un œil de chèvre devant ton boss", pctA: 29 },
  { id: 239, a: "sucer un furoncle éclaté pendant 5 minutes", b: "te faire sodomiser par une chèvre devant tes parents", pctA: 73 },
  { id: 240, a: "embrasser avec la langue les aisselles non rasées d'un SDF en filmant", b: "te gargariser avec du vomi de chien devant ta famille", pctA: 16 },
  { id: 241, a: "te gargariser avec du vomi de chien au réveil", b: "masturber un extraterrestre tentaculaire dans une église", pctA: 34 },
  { id: 242, a: "péter bruyamment à ton mariage et faire comme si de rien n'était", b: "te faire doigter par ton boss au supermarché", pctA: 41 },
  { id: 243, a: "te brûler le mamelon lentement", b: "plonger nu dans du fumier avec des plaies ouvertes", pctA: 72 },
  { id: 244, a: "coucher avec un nain de jardin devant tes parents", b: "masturber ton cousin germain devant tes parents", pctA: 57 },
  { id: 245, a: "masturber une chèvre en direct sur Twitch", b: "te pisser dessus en serrant la main du président en pleurant", pctA: 66 },
  { id: 246, a: "te pisser dessus dans le métro bondé en pleurant", b: "te faire doigter par une personne qui a la lèpre sur la place publique", pctA: 69 },
  { id: 247, a: "déguster un tampon usagé sans boire d'eau", b: "coucher avec un sans-abri édenté en direct sur Twitch", pctA: 55 },
  { id: 248, a: "t'enfoncer une aiguille dans les lèvres sans anesthésie", b: "te rouler dans du goudron bouillant avec des plaies ouvertes", pctA: 23 },
  { id: 249, a: "vomir aux funérailles de ta mère en hurlant", b: "éjaculer aux funérailles de ta mère en hurlant", pctA: 30 },
  { id: 250, a: "manger des asticots sans boire d'eau", b: "sucer un furoncle éclaté avec passion", pctA: 47 },
  { id: 251, a: "faire l'amour dans le cadavre de ton animal de compagnie", b: "transpirer du jus de poubelle", pctA: 16 },
  { id: 252, a: "trouver de la morve verte épaisse dans ta soupe au restaurant", b: "utiliser du sperme de cheval comme lubrifiant", pctA: 87 },
  { id: 253, a: "devoir faire une présentation PowerPoint au travail sur te masturber avec des fruits pourris", b: "te rincer la bouche avec de la sueur de sumo", pctA: 51 },
  { id: 254, a: "t'asseoir nu sur un essaim de guêpes", b: "devoir cuisiner tous tes repas avec du fromage de bite", pctA: 87 },
  { id: 255, a: "devoir te masturber en regardant ta propre grand-mère", b: "te rincer la bouche avec de la diarrhée de chien", pctA: 18 },
  { id: 256, a: "coucher avec un sans-abri qui n'a pas pris de douche depuis 10 ans sans préservatif", b: "éternuer des croûtes de plaies infectées", pctA: 24 },
  { id: 257, a: "avoir un essaim de guêpes coincé(e) dans l'urètre", b: "transpirer de la diarrhée de chien", pctA: 47 },
  { id: 258, a: "transpirer de la sauce soja", b: "avoir une poignée de punaises qui te pousse dans la gorge", pctA: 35 },
  { id: 259, a: "éternuer du cérumen noir", b: "devoir masser tes parents avec du sang menstruel caillé", pctA: 94 },
  { id: 260, a: "remplacer ton shampoing par des glaires de fumeur", b: "te rincer la bouche avec des poils pubiens trouvés dans les douches publiques", pctA: 27 },
  { id: 261, a: "devoir marcher pieds nus sur une brosse métallique", b: "devoir glisser du papier de verre grain 40 sous tes ongles", pctA: 31 },
  { id: 262, a: "remplacer ton shampoing par du smegma séché", b: "devoir faire une présentation PowerPoint au travail sur te frotter les parties génitales sur la poignée de porte", pctA: 56 },
  { id: 263, a: "faire un gargarisme avec des excréments d'oiseau", b: "recevoir un coup de pied dans les boules par un essaim de guêpes", pctA: 54 },
  { id: 264, a: "avoir du piment habanero coupé en deux qui te pousse dans la gorge", b: "utiliser de la bave de crapaud comme lubrifiant", pctA: 60 },
  { id: 265, a: "devoir lécher les pieds de une poubelle de restaurant d'autoroute", b: "avoir un fétichisme incontrôlable pour un sans-abri qui n'a pas pris de douche depuis 10 ans", pctA: 44 },
  { id: 266, a: "faire un gargarisme avec des glaires de fumeur", b: "avoir des sécrétions qui sentent du pus d'un inconnu", pctA: 19 },
  { id: 267, a: "te laver le visage avec du sang menstruel caillé", b: "te faire sodomiser par un chimpanzé en rut", pctA: 26 },
  { id: 268, a: "remplacer ton shampoing par de la bave de crapaud", b: "devoir masser tes parents avec du pus d'un inconnu", pctA: 47 },
  { id: 269, a: "trouver de la pisse d'asthmatique dans ta soupe au restaurant", b: "prendre un bain rempli de du liquide amniotique", pctA: 44 },
  { id: 270, a: "remplacer ton shampoing par des poils pubiens trouvés dans les douches publiques", b: "avoir des sécrétions qui sentent du vomi de bébé", pctA: 91 },
  { id: 271, a: "avoir un fétichisme incontrôlable pour ton pire ennemi couvert de selles", b: "devoir cuisiner tous tes repas avec du cérumen noir", pctA: 89 },
  { id: 272, a: "devoir cuisiner tous tes repas avec de la diarrhée de chien", b: "te frotter les yeux avec un cactus en feu", pctA: 53 },
  { id: 273, a: "éternuer des poils pubiens trouvés dans les douches publiques", b: "prendre un bain rempli de des glaires de fumeur", pctA: 85 },
  { id: 274, a: "découvrir du sperme de cheval dans ton slip chaque matin", b: "faire un gargarisme avec du vomi de bébé", pctA: 39 },
  { id: 275, a: "te frotter les yeux avec du papier de verre grain 40", b: "devoir cuisiner tous tes repas avec des excréments d'oiseau", pctA: 26 },
  { id: 276, a: "pleurer du smegma séché quand tu es triste", b: "te faire arracher une brosse métallique", pctA: 87 },
  { id: 277, a: "faire un plan à trois avec un prêtre en pleine messe", b: "devoir cuisiner tous tes repas avec des croûtes de plaies infectées", pctA: 48 },
  { id: 278, a: "dormir dans des draps imbibés de du sperme de cheval", b: "devoir cuisiner tous tes repas avec des poils pubiens trouvés dans les douches publiques", pctA: 37 },
  { id: 279, a: "avoir des sécrétions qui sentent du smegma séché", b: "avoir des sécrétions qui sentent des pellicules grasses", pctA: 86 },
  { id: 280, a: "saigner du liquide amniotique au lieu de sang", b: "avoir des lames de rasoir rouillées qui te pousse dans la gorge", pctA: 88 },
  { id: 281, a: "prendre un bain rempli de du jus de poubelle", b: "te faire arracher un tesson de bouteille", pctA: 56 },
  { id: 282, a: "te brosser les dents avec du smegma séché", b: "saigner de la bave de crapaud au lieu de sang", pctA: 48 },
  { id: 283, a: "découvrir de la bave de crapaud dans ton slip chaque matin", b: "avoir un ours en colère qui te pousse dans la gorge", pctA: 51 },
  { id: 284, a: "devoir sucer un sans-abri qui n'a pas pris de douche depuis 10 ans", b: "saigner de la pisse d'asthmatique au lieu de sang", pctA: 16 },
  { id: 285, a: "recevoir un coup de pied dans les boules par du papier de verre grain 40", b: "saigner des rognures d'ongles de pieds au lieu de sang", pctA: 57 },
  { id: 286, a: "prendre un bain rempli de du cérumen noir", b: "devoir expliquer à ta mère pourquoi tu aimes regarder du porno impliquant des nains unijambistes", pctA: 44 },
  { id: 287, a: "devoir marcher pieds nus sur du piment habanero coupé en deux", b: "devoir masser tes parents avec de la bave de crapaud", pctA: 53 },
  { id: 288, a: "transpirer des glaires de fumeur", b: "devoir masser tes parents avec du sperme de cheval", pctA: 75 },
  { id: 289, a: "utiliser des pellicules grasses comme lubrifiant", b: "laisser accidentellement un message vocal à ton ex en plein pleurer pendant l'acte sexuel", pctA: 20 },
  { id: 290, a: "utiliser des excréments d'oiseau comme lubrifiant", b: "transpirer du cérumen noir", pctA: 81 },
  { id: 291, a: "éternuer de la sueur de sumo", b: "te faire surprendre par ton patron en train de regarder du porno impliquant des nains unijambistes", pctA: 15 },
  { id: 292, a: "prendre un bain rempli de des rognures d'ongles de pieds", b: "devoir crier à chaque orgasme : te masturber avec des fruits pourris", pctA: 44 },
  { id: 293, a: "te laver le visage avec du cérumen noir", b: "coucher avec ton pire ennemi couvert de selles sans préservatif", pctA: 42 },
  { id: 294, a: "devoir avaler des glaires de fumeur", b: "pleurer du liquide amniotique quand tu es triste", pctA: 24 },
  { id: 295, a: "faire un plan à trois avec une fosse septique qui déborde", b: "te faire arracher des lames de rasoir rouillées", pctA: 90 },
  { id: 296, a: "te rincer la bouche avec de la bave de crapaud", b: "utiliser du cérumen noir comme lubrifiant", pctA: 27 },
  { id: 297, a: "faire l'amour dans un chimpanzé en rut", b: "te rincer la bouche avec du sang menstruel caillé", pctA: 90 },
  { id: 298, a: "te faire surprendre par ton patron en train de péter dans un bocal pour le respirer plus tard", b: "te rincer la bouche avec du sperme de cheval", pctA: 87 },
  { id: 299, a: "devoir glisser une seringue rouillée sous tes ongles", b: "devoir marcher pieds nus sur un cactus en feu", pctA: 86 },
  { id: 300, a: "saigner des pellicules grasses au lieu de sang", b: "être connu mondialement comme la personne qui adore te lécher le trou du cul", pctA: 27 },
  { id: 301, a: "découvrir du cérumen noir dans ton slip chaque matin", b: "éternuer du sperme de cheval", pctA: 52 },
  { id: 302, a: "te rincer la bouche avec des excréments d'oiseau", b: "devoir sucer ton pire ennemi couvert de selles", pctA: 88 },
  { id: 303, a: "te faire sodomiser par une fosse septique qui déborde", b: "prendre un bain rempli de du fromage de bite", pctA: 89 },
  { id: 304, a: "avoir des sécrétions qui sentent des poils pubiens trouvés dans les douches publiques", b: "te faire vomir dessus par un ivrogne", pctA: 27 },
  { id: 305, a: "diffuser en direct sur Facebook une vidéo de toi en train de baiser un melon", b: "trouver du sang menstruel caillé dans ta soupe au restaurant", pctA: 22 },
  { id: 306, a: "utiliser du smegma séché comme lubrifiant", b: "saigner de la sueur de sumo au lieu de sang", pctA: 95 },
  { id: 307, a: "te laver le visage avec du vomi de bébé", b: "devoir avaler du vomi de bébé", pctA: 52 },
  { id: 308, a: "te brosser les dents avec du pus d'un inconnu", b: "que ton historique de navigation montre que tu cherches souvent comment renifler des culottes sales", pctA: 44 },
  { id: 309, a: "laisser accidentellement un message vocal à ton ex en plein regarder du porno impliquant des nains unijambistes", b: "éternuer du fromage de bite", pctA: 44 },
  { id: 310, a: "diffuser en direct sur Facebook une vidéo de toi en train de péter dans un bocal pour le respirer plus tard", b: "trouver du vomi de bébé dans ta soupe au restaurant", pctA: 51 },
  { id: 311, a: "te rincer la bouche avec du cérumen noir", b: "faire l'amour dans une poubelle de restaurant d'autoroute", pctA: 57 },
  { id: 312, a: "pleurer du sang menstruel caillé quand tu es triste", b: "devoir masser tes parents avec du jus de poubelle", pctA: 91 },
  { id: 313, a: "avoir des vers solitaires qui sortent de ton nez", b: "avoir un tesson de bouteille coincé(e) dans l'urètre", pctA: 48 },
  { id: 314, a: "te brosser les dents avec de la pisse d'asthmatique", b: "remplacer ton shampoing par du fromage de bite", pctA: 52 },
  { id: 315, a: "devoir avaler des poils pubiens trouvés dans les douches publiques", b: "te frotter les yeux avec une poignée de punaises", pctA: 26 },
  { id: 316, a: "recevoir un coup de pied dans les boules par des lames de rasoir rouillées", b: "devoir faire une présentation PowerPoint au travail sur te lécher le trou du cul", pctA: 92 },
  { id: 317, a: "utiliser du sang menstruel caillé comme lubrifiant", b: "devoir avaler des croûtes de plaies infectées", pctA: 42 },
  { id: 318, a: "coucher avec un chimpanzé en rut sans préservatif", b: "te brosser les dents avec de la bave de crapaud", pctA: 78 },
  { id: 319, a: "faire un gargarisme avec du jus de poubelle", b: "remplacer ton shampoing par du jus de poubelle", pctA: 45 },
  { id: 320, a: "trouver des rognures d'ongles de pieds dans ta soupe au restaurant", b: "que ton historique de navigation montre que tu cherches souvent comment te frotter les parties génitales sur la poignée de porte", pctA: 86 },
  { id: 321, a: "devoir masser tes parents avec du cérumen noir", b: "te frotter les yeux avec un tesson de bouteille", pctA: 44 },
  { id: 322, a: "coucher avec un cadavre en décomposition sans préservatif", b: "avoir des dents en caoutchouc", pctA: 60 },
  { id: 323, a: "avoir des sécrétions qui sentent de la sueur de sumo", b: "devoir cuisiner tous tes repas avec des rognures d'ongles de pieds", pctA: 83 },
  { id: 324, a: "transpirer des poils pubiens trouvés dans les douches publiques", b: "trouver du liquide amniotique dans ta soupe au restaurant", pctA: 88 },
  { id: 325, a: "faire un gargarisme avec de la sueur de sumo", b: "devoir masser tes parents avec des rognures d'ongles de pieds", pctA: 60 },
  { id: 326, a: "coucher avec un prêtre en pleine messe sans préservatif", b: "découvrir du pus d'un inconnu dans ton slip chaque matin", pctA: 82 },
  { id: 327, a: "dormir dans des draps imbibés de de la bave de crapaud", b: "devoir masser tes parents avec de la diarrhée de chien", pctA: 40 },
  { id: 328, a: "devoir porter un t-shirt au mariage de ta sœur disant : baiser un melon", b: "te faire sodomiser par un sans-abri qui n'a pas pris de douche depuis 10 ans", pctA: 42 },
  { id: 329, a: "saigner du sperme de cheval au lieu de sang", b: "devoir cuisiner tous tes repas avec des pellicules grasses", pctA: 28 },
  { id: 330, a: "utiliser du jus de poubelle comme lubrifiant", b: "te brosser les dents avec du cérumen noir", pctA: 38 },
  { id: 331, a: "devoir marcher pieds nus sur du papier de verre grain 40", b: "devoir te masturber en regardant une poubelle de restaurant d'autoroute", pctA: 59 },
  { id: 332, a: "devoir lécher les pieds de un cadavre en décomposition", b: "saigner des poils pubiens trouvés dans les douches publiques au lieu de sang", pctA: 17 },
  { id: 333, a: "avoir un tatouage sur le front qui dit : te lécher le trou du cul", b: "t'asseoir nu sur du papier de verre grain 40", pctA: 16 },
  { id: 334, a: "trouver du jus de poubelle dans ta soupe au restaurant", b: "devoir sucer un cadavre en décomposition", pctA: 51 },
  { id: 335, a: "te rincer la bouche avec de la pisse d'asthmatique", b: "dormir dans des draps imbibés de des rognures d'ongles de pieds", pctA: 78 },
  { id: 336, a: "devoir cuisiner tous tes repas avec du sperme de cheval", b: "pleurer du sperme de cheval quand tu es triste", pctA: 44 },
  { id: 337, a: "t'asseoir nu sur une poignée de punaises", b: "te rincer la bouche avec du vomi de bébé", pctA: 19 },
  { id: 338, a: "avoir un tatouage sur le front qui dit : renifler des culottes sales", b: "avoir des sécrétions qui sentent de la morve verte épaisse", pctA: 88 },
  { id: 339, a: "coucher avec une poubelle de restaurant d'autoroute sans préservatif", b: "pleurer des croûtes de plaies infectées quand tu es triste", pctA: 83 },
  { id: 340, a: "devoir avaler du jus de poubelle", b: "pleurer du fromage de bite quand tu es triste", pctA: 68 },
  { id: 341, a: "te faire surprendre par ton patron en train de pleurer pendant l'acte sexuel", b: "trouver des poils pubiens trouvés dans les douches publiques dans ta soupe au restaurant", pctA: 89 },
  { id: 342, a: "devoir cuisiner tous tes repas avec du jus de poubelle", b: "te faire surprendre par ton patron en train de te masturber avec des fruits pourris", pctA: 76 },
  { id: 343, a: "transpirer des croûtes de plaies infectées", b: "te faire surprendre par ton patron en train de te frotter les parties génitales sur la poignée de porte", pctA: 64 },
  { id: 344, a: "faire un gargarisme avec du cérumen noir", b: "devoir marcher pieds nus sur une poignée de punaises", pctA: 48 },
  { id: 345, a: "recevoir un coup de pied dans les boules par du piment habanero coupé en deux", b: "devoir avaler du sperme de cheval", pctA: 57 },
  { id: 346, a: "te laver le visage avec de la pisse d'asthmatique", b: "prendre un bain rempli de de la pisse d'asthmatique", pctA: 37 },
  { id: 347, a: "faire un gargarisme avec du fromage de bite", b: "diffuser en direct sur Facebook une vidéo de toi en train de te lécher le trou du cul", pctA: 18 },
  { id: 348, a: "te brosser les dents avec des rognures d'ongles de pieds", b: "recevoir un coup de pied dans les boules par une seringue rouillée", pctA: 95 },
  { id: 349, a: "devoir porter un t-shirt au mariage de ta sœur disant : te masturber avec des fruits pourris", b: "diffuser en direct sur Facebook une vidéo de toi en train de te doigter dans les toilettes du bureau", pctA: 88 },
  { id: 350, a: "prendre un bain rempli de des poils pubiens trouvés dans les douches publiques", b: "saigner du fromage de bite au lieu de sang", pctA: 27 },
  { id: 351, a: "te laver le visage avec des excréments d'oiseau", b: "devoir cuisiner tous tes repas avec de la sueur de sumo", pctA: 48 },
  { id: 352, a: "t'asseoir nu sur une seringue rouillée", b: "te brosser les dents avec des glaires de fumeur", pctA: 62 },
  { id: 353, a: "faire un gargarisme avec de la morve verte épaisse", b: "éternuer de la diarrhée de chien", pctA: 92 },
  { id: 354, a: "devoir avaler de la sueur de sumo", b: "te rincer la bouche avec du fromage de bite", pctA: 30 },
  { id: 355, a: "être connu mondialement comme la personne qui adore regarder du porno impliquant des nains unijambistes", b: "dormir dans des draps imbibés de du smegma séché", pctA: 20 },
  { id: 356, a: "devoir glisser du piment habanero coupé en deux sous tes ongles", b: "laisser accidentellement un message vocal à ton ex en plein baiser un melon", pctA: 59 },
  { id: 357, a: "prendre un bain rempli de des excréments d'oiseau", b: "te laver le visage avec du fromage de bite", pctA: 57 },
  { id: 358, a: "découvrir du vomi de bébé dans ton slip chaque matin", b: "devoir crier à chaque orgasme : manger tes propres crottes de nez", pctA: 92 },
  { id: 359, a: "t'asseoir nu sur du piment habanero coupé en deux", b: "éternuer du vomi de bébé", pctA: 52 },
  { id: 360, a: "utiliser de la diarrhée de chien comme lubrifiant", b: "devoir avaler de la pisse d'asthmatique", pctA: 57 },
  { id: 361, a: "te brosser les dents avec du fromage de bite", b: "prendre un bain rempli de de la morve verte épaisse", pctA: 21 },
  { id: 362, a: "devoir sucer un chimpanzé en rut", b: "faire un gargarisme avec du sperme de cheval", pctA: 95 },
  { id: 363, a: "que ton historique de navigation montre que tu cherches souvent comment baiser un melon", b: "pleurer des pellicules grasses quand tu es triste", pctA: 46 },
  { id: 364, a: "vomir des limaces vivantes", b: "te frotter les yeux avec un ours en colère", pctA: 88 },
  { id: 365, a: "prendre un bain rempli de des croûtes de plaies infectées", b: "avoir un tatouage sur le front qui dit : regarder du porno impliquant des nains unijambistes", pctA: 67 },
  { id: 366, a: "recevoir un coup de pied dans les boules par une brosse métallique", b: "utiliser du fromage de bite comme lubrifiant", pctA: 20 },
  { id: 367, a: "te frotter les yeux avec des lames de rasoir rouillées", b: "devoir lécher les pieds de le cadavre de ton animal de compagnie", pctA: 22 },
  { id: 368, a: "te brosser les dents avec de la morve verte épaisse", b: "te frotter les yeux avec un essaim de guêpes", pctA: 52 },
  { id: 369, a: "éternuer du smegma séché", b: "devoir sucer le cadavre de ton animal de compagnie", pctA: 42 },
  { id: 370, a: "péter de la fumée noire toxique", b: "faire un gargarisme avec des croûtes de plaies infectées", pctA: 56 },
  { id: 371, a: "découvrir du liquide amniotique dans ton slip chaque matin", b: "te laver le visage avec des pellicules grasses", pctA: 15 },
  { id: 372, a: "faire l'amour dans un cadavre en décomposition", b: "devoir masser tes parents avec des poils pubiens trouvés dans les douches publiques", pctA: 86 },
  { id: 373, a: "te brosser les dents avec du sang menstruel caillé", b: "te faire sodomiser par un clown tueur", pctA: 60 },
  { id: 374, a: "transpirer de la sueur de sumo", b: "devoir te masturber en regardant une fosse septique qui déborde", pctA: 20 },
  { id: 375, a: "éternuer des rognures d'ongles de pieds", b: "faire l'amour dans ton pire ennemi couvert de selles", pctA: 94 },
  { id: 376, a: "faire un plan à trois avec ton pire ennemi couvert de selles", b: "te laver le visage avec des rognures d'ongles de pieds", pctA: 44 },
  { id: 377, a: "être connu mondialement comme la personne qui adore te frotter les parties génitales sur la poignée de porte", b: "uriner des glaçons", pctA: 76 },
  { id: 378, a: "trouver du smegma séché dans ta soupe au restaurant", b: "devoir marcher pieds nus sur un ours en colère", pctA: 95 },
  { id: 379, a: "te rincer la bouche avec du jus de poubelle", b: "avoir un fétichisme incontrôlable pour un clown tueur", pctA: 59 },
  { id: 380, a: "transpirer des pellicules grasses", b: "dormir dans des draps imbibés de de la pisse d'asthmatique", pctA: 59 },
  { id: 381, a: "utiliser du pus d'un inconnu comme lubrifiant", b: "te frotter les yeux avec une seringue rouillée", pctA: 74 },
  { id: 382, a: "avoir des testicules de la taille d'une pastèque", b: "devoir te masturber en regardant ton pire ennemi couvert de selles", pctA: 95 },
  { id: 383, a: "devoir te masturber en regardant un sans-abri qui n'a pas pris de douche depuis 10 ans", b: "utiliser des croûtes de plaies infectées comme lubrifiant", pctA: 90 },
  { id: 384, a: "te faire arracher une poignée de punaises", b: "te faire arracher un cactus en feu", pctA: 91 },
  { id: 385, a: "devoir faire une présentation PowerPoint au travail sur manger tes propres crottes de nez", b: "dormir dans des draps imbibés de des excréments d'oiseau", pctA: 55 },
  { id: 386, a: "avoir un fétichisme incontrôlable pour ta propre grand-mère", b: "éternuer du jus de poubelle", pctA: 86 },
  { id: 387, a: "devoir sucer une poubelle de restaurant d'autoroute", b: "pleurer des excréments d'oiseau quand tu es triste", pctA: 57 },
  { id: 388, a: "trouver des pellicules grasses dans ta soupe au restaurant", b: "dormir dans des draps imbibés de du pus d'un inconnu", pctA: 94 },
  { id: 389, a: "devoir masser tes parents avec des glaires de fumeur", b: "faire un gargarisme avec du sang menstruel caillé", pctA: 88 },
  { id: 390, a: "avoir du papier de verre grain 40 qui te pousse dans la gorge", b: "coucher avec le cadavre de ton animal de compagnie sans préservatif", pctA: 85 },
  { id: 391, a: "devoir avaler des rognures d'ongles de pieds", b: "pleurer de la bave de crapaud quand tu es triste", pctA: 20 },
  { id: 392, a: "devoir masser tes parents avec du liquide amniotique", b: "devoir faire une présentation PowerPoint au travail sur péter dans un bocal pour le respirer plus tard", pctA: 94 },
  { id: 393, a: "trouver de la sueur de sumo dans ta soupe au restaurant", b: "sucer un tampon usagé", pctA: 15 },
  { id: 394, a: "utiliser des glaires de fumeur comme lubrifiant", b: "faire un plan à trois avec un chimpanzé en rut", pctA: 55 },
  { id: 395, a: "faire un plan à trois avec un cadavre en décomposition", b: "avoir un tatouage sur le front qui dit : te masturber avec des fruits pourris", pctA: 60 },
  { id: 396, a: "te laver le visage avec du sperme de cheval", b: "avoir un essaim de guêpes qui te pousse dans la gorge", pctA: 59 },
  { id: 397, a: "te laver le visage avec de la bave de crapaud", b: "te rincer la bouche avec des croûtes de plaies infectées", pctA: 15 },
  { id: 398, a: "éternuer de la pisse d'asthmatique", b: "avoir une seringue rouillée qui te pousse dans la gorge", pctA: 94 },
  { id: 399, a: "avoir un fétichisme incontrôlable pour une fosse septique qui déborde", b: "avoir un tatouage sur le front qui dit : péter dans un bocal pour le respirer plus tard", pctA: 20 },
  { id: 400, a: "te faire arracher un ours en colère", b: "avoir un ours en colère coincé(e) dans l'urètre", pctA: 42 },
  { id: 401, a: "pleurer du sang chaque fois que tu es excité", b: "devoir crier à chaque orgasme : péter dans un bocal pour le respirer plus tard", pctA: 66 },
  { id: 402, a: "devoir avaler de la morve verte épaisse", b: "trouver du cérumen noir dans ta soupe au restaurant", pctA: 51 },
  { id: 403, a: "utiliser du liquide amniotique comme lubrifiant", b: "utiliser des poils pubiens trouvés dans les douches publiques comme lubrifiant", pctA: 30 },
  { id: 404, a: "utiliser de la morve verte épaisse comme lubrifiant", b: "dormir dans des draps imbibés de du liquide amniotique", pctA: 60 },
  { id: 405, a: "devoir avaler de la diarrhée de chien", b: "devoir te torcher avec du papier d'aluminium", pctA: 40 },
  { id: 406, a: "avoir une poignée de punaises coincé(e) dans l'urètre", b: "devoir sucer un clown tueur", pctA: 93 },
  { id: 407, a: "faire un gargarisme avec de la pisse d'asthmatique", b: "avoir une seringue rouillée coincé(e) dans l'urètre", pctA: 86 },
  { id: 408, a: "t'asseoir nu sur une brosse métallique", b: "dormir dans des draps imbibés de du fromage de bite", pctA: 18 },
  { id: 409, a: "pleurer de la sueur de sumo quand tu es triste", b: "découvrir de la diarrhée de chien dans ton slip chaque matin", pctA: 40 },
  { id: 410, a: "faire un plan à trois avec une poubelle de restaurant d'autoroute", b: "te faire arracher du papier de verre grain 40", pctA: 26 },
  { id: 411, a: "devoir cuisiner tous tes repas avec du sang menstruel caillé", b: "devoir avaler du cérumen noir", pctA: 23 },
  { id: 412, a: "remplacer ton shampoing par du liquide amniotique", b: "te laver le visage avec des poils pubiens trouvés dans les douches publiques", pctA: 55 },
  { id: 413, a: "devoir crier à chaque orgasme : baiser un melon", b: "devoir crier à chaque orgasme : te lécher le trou du cul", pctA: 22 },
  { id: 414, a: "saigner de la morve verte épaisse au lieu de sang", b: "devoir glisser un essaim de guêpes sous tes ongles", pctA: 54 },
  { id: 415, a: "te faire sodomiser par ton pire ennemi couvert de selles", b: "devoir masser tes parents avec de la morve verte épaisse", pctA: 95 },
  { id: 416, a: "prendre un bain rempli de du smegma séché", b: "devoir faire une présentation PowerPoint au travail sur regarder du porno impliquant des nains unijambistes", pctA: 86 },
  { id: 417, a: "avoir un fétichisme incontrôlable pour un cadavre en décomposition", b: "recevoir un coup de pied dans les boules par un tesson de bouteille", pctA: 91 },
  { id: 418, a: "te brosser les dents avec des pellicules grasses", b: "transpirer du pus d'un inconnu", pctA: 56 },
  { id: 419, a: "te rincer la bouche avec de la morve verte épaisse", b: "être connu mondialement comme la personne qui adore pleurer pendant l'acte sexuel", pctA: 87 },
  { id: 420, a: "utiliser des rognures d'ongles de pieds comme lubrifiant", b: "avoir des spaghettis à la place des poils pubiens", pctA: 27 },
  { id: 421, a: "devoir porter un t-shirt au mariage de ta sœur disant : pleurer pendant l'acte sexuel", b: "transpirer des excréments d'oiseau", pctA: 36 },
  { id: 422, a: "éternuer du pus d'un inconnu", b: "devoir masser tes parents avec des pellicules grasses", pctA: 15 },
  { id: 423, a: "te brosser les dents avec de la sueur de sumo", b: "te laver le visage avec de la morve verte épaisse", pctA: 89 },
  { id: 424, a: "diffuser en direct sur Facebook une vidéo de toi en train de regarder du porno impliquant des nains unijambistes", b: "faire un plan à trois avec un clown tueur", pctA: 78 },
  { id: 425, a: "dormir dans des draps imbibés de du sang menstruel caillé", b: "devoir masser tes parents avec des excréments d'oiseau", pctA: 94 },
  { id: 426, a: "avoir des tétons qui clignotent dans le noir", b: "te laver le visage avec des glaires de fumeur", pctA: 44 },
  { id: 427, a: "éternuer des excréments d'oiseau", b: "te rincer la bouche avec du liquide amniotique", pctA: 26 },
  { id: 428, a: "devoir cuisiner tous tes repas avec de la bave de crapaud", b: "devoir expliquer à ta mère pourquoi tu aimes te frotter les parties génitales sur la poignée de porte", pctA: 87 },
  { id: 429, a: "devoir avaler des pellicules grasses", b: "faire l'amour dans un sans-abri qui n'a pas pris de douche depuis 10 ans", pctA: 58 },
  { id: 430, a: "devoir faire une présentation PowerPoint au travail sur pleurer pendant l'acte sexuel", b: "déféquer des clous rouillés", pctA: 22 },
  { id: 431, a: "avoir des sécrétions qui sentent du sperme de cheval", b: "laisser accidentellement un message vocal à ton ex en plein manger tes propres crottes de nez", pctA: 28 },
  { id: 432, a: "devoir crier à chaque orgasme : pleurer pendant l'acte sexuel", b: "remplacer ton shampoing par de la sueur de sumo", pctA: 29 },
  { id: 433, a: "recevoir un coup de pied dans les boules par un ours en colère", b: "devoir cuisiner tous tes repas avec du pus d'un inconnu", pctA: 25 },
  { id: 434, a: "devoir faire une présentation PowerPoint au travail sur te doigter dans les toilettes du bureau", b: "diffuser en direct sur Facebook une vidéo de toi en train de manger tes propres crottes de nez", pctA: 94 },
  { id: 435, a: "devoir cuisiner tous tes repas avec du vomi de bébé", b: "devoir lécher les pieds de un chimpanzé en rut", pctA: 27 },
  { id: 436, a: "pleurer des glaires de fumeur quand tu es triste", b: "dormir dans des draps imbibés de des pellicules grasses", pctA: 94 },
  { id: 437, a: "devoir masser tes parents avec du fromage de bite", b: "saigner du smegma séché au lieu de sang", pctA: 28 },
  { id: 438, a: "découvrir du jus de poubelle dans ton slip chaque matin", b: "prendre un bain rempli de de la sueur de sumo", pctA: 53 },
  { id: 439, a: "avoir des sécrétions qui sentent du sang menstruel caillé", b: "pleurer de la morve verte épaisse quand tu es triste", pctA: 47 },
  { id: 440, a: "avoir une langue qui fait 3 mètres de long", b: "devoir lécher les pieds de ta propre grand-mère", pctA: 46 },
  { id: 441, a: "devoir masser tes parents avec des croûtes de plaies infectées", b: "transpirer de la pisse d'asthmatique", pctA: 58 },
  { id: 442, a: "pleurer du cérumen noir quand tu es triste", b: "dormir dans des draps imbibés de du cérumen noir", pctA: 85 },
  { id: 443, a: "te faire arracher un essaim de guêpes", b: "saigner du sang menstruel caillé au lieu de sang", pctA: 88 },
  { id: 444, a: "utiliser de la sueur de sumo comme lubrifiant", b: "recevoir un coup de pied dans les boules par une poignée de punaises", pctA: 49 },
  { id: 445, a: "éternuer du sang menstruel caillé", b: "devoir marcher pieds nus sur un tesson de bouteille", pctA: 86 },
  { id: 446, a: "devoir te masturber en regardant le cadavre de ton animal de compagnie", b: "devoir te masturber en regardant un chimpanzé en rut", pctA: 86 },
  { id: 447, a: "laisser accidentellement un message vocal à ton ex en plein te lécher le trou du cul", b: "devoir lécher les pieds de ton pire ennemi couvert de selles", pctA: 86 },
  { id: 448, a: "devoir avaler des excréments d'oiseau", b: "devoir expliquer à ta mère pourquoi tu aimes péter dans un bocal pour le respirer plus tard", pctA: 17 },
  { id: 449, a: "avoir du piment habanero coupé en deux coincé(e) dans l'urètre", b: "te faire arracher du piment habanero coupé en deux", pctA: 49 },
  { id: 450, a: "avoir des branchies sur le cou qui suintent de la vase", b: "faire un gargarisme avec de la diarrhée de chien", pctA: 62 },
  { id: 451, a: "te faire surprendre par ton patron en train de te doigter dans les toilettes du bureau", b: "que ton historique de navigation montre que tu cherches souvent comment manger tes propres crottes de nez", pctA: 59 },
  { id: 452, a: "devoir masser tes parents avec du vomi de bébé", b: "pleurer des rognures d'ongles de pieds quand tu es triste", pctA: 55 },
  { id: 453, a: "découvrir du fromage de bite dans ton slip chaque matin", b: "que ton historique de navigation montre que tu cherches souvent comment te lécher le trou du cul", pctA: 50 },
  { id: 454, a: "te rincer la bouche avec des rognures d'ongles de pieds", b: "te brosser les dents avec du liquide amniotique", pctA: 24 },
  { id: 455, a: "devoir masser tes parents avec du smegma séché", b: "devoir marcher pieds nus sur un essaim de guêpes", pctA: 60 },
  { id: 456, a: "découvrir du smegma séché dans ton slip chaque matin", b: "devoir avaler du fromage de bite", pctA: 41 },
  { id: 457, a: "te brosser les dents avec des poils pubiens trouvés dans les douches publiques", b: "que ton historique de navigation montre que tu cherches souvent comment péter dans un bocal pour le respirer plus tard", pctA: 60 },
  { id: 458, a: "prendre un bain rempli de du sperme de cheval", b: "te faire sodomiser par une poubelle de restaurant d'autoroute", pctA: 43 },
  { id: 459, a: "que ton historique de navigation montre que tu cherches souvent comment te masturber avec des fruits pourris", b: "faire un gargarisme avec des poils pubiens trouvés dans les douches publiques", pctA: 49 },
  { id: 460, a: "être connu mondialement comme la personne qui adore renifler des culottes sales", b: "faire l'amour dans une fosse septique qui déborde", pctA: 68 },
  { id: 461, a: "être connu mondialement comme la personne qui adore te doigter dans les toilettes du bureau", b: "devoir te masturber en regardant un clown tueur", pctA: 92 },
  { id: 462, a: "te laver le visage avec du jus de poubelle", b: "trouver des excréments d'oiseau dans ta soupe au restaurant", pctA: 30 },
  { id: 463, a: "devoir masser tes parents avec de la sueur de sumo", b: "te faire sodomiser par un cadavre en décomposition", pctA: 20 },
  { id: 464, a: "devoir porter un t-shirt au mariage de ta sœur disant : péter dans un bocal pour le respirer plus tard", b: "diffuser en direct sur Facebook une vidéo de toi en train de te frotter les parties génitales sur la poignée de porte", pctA: 42 },
  { id: 465, a: "devoir expliquer à ta mère pourquoi tu aimes te doigter dans les toilettes du bureau", b: "avoir des sécrétions qui sentent des glaires de fumeur", pctA: 90 },
  { id: 466, a: "prendre un bain rempli de du vomi de bébé", b: "saigner des croûtes de plaies infectées au lieu de sang", pctA: 88 },
  { id: 467, a: "faire l'amour dans un prêtre en pleine messe", b: "devoir crier à chaque orgasme : renifler des culottes sales", pctA: 41 },
  { id: 468, a: "trouver de la diarrhée de chien dans ta soupe au restaurant", b: "remplacer ton shampoing par du vomi de bébé", pctA: 94 },
  { id: 469, a: "éjaculer de la mayonnaise périmée", b: "t'asseoir nu sur des lames de rasoir rouillées", pctA: 54 },
  { id: 470, a: "découvrir des pellicules grasses dans ton slip chaque matin", b: "trouver des croûtes de plaies infectées dans ta soupe au restaurant", pctA: 23 },
  { id: 471, a: "te brosser les dents avec du jus de poubelle", b: "prendre un bain rempli de du pus d'un inconnu", pctA: 57 },
  { id: 472, a: "trouver de la bave de crapaud dans ta soupe au restaurant", b: "devoir cuisiner tous tes repas avec du liquide amniotique", pctA: 55 },
  { id: 473, a: "devoir sucer un prêtre en pleine messe", b: "te brosser les dents avec de la diarrhée de chien", pctA: 46 },
  { id: 474, a: "que ton pet sente toujours le cadavre", b: "te frotter les yeux avec du piment habanero coupé en deux", pctA: 92 },
  { id: 475, a: "devoir lécher les pieds de un clown tueur", b: "devoir glisser une brosse métallique sous tes ongles", pctA: 95 },
  { id: 476, a: "laisser accidentellement un message vocal à ton ex en plein te masturber avec des fruits pourris", b: "te frotter les yeux avec une brosse métallique", pctA: 88 },
  { id: 477, a: "prendre un bain rempli de des pellicules grasses", b: "te faire surprendre par ton patron en train de renifler des culottes sales", pctA: 94 },
  { id: 478, a: "laisser accidentellement un message vocal à ton ex en plein te doigter dans les toilettes du bureau", b: "devoir expliquer à ta mère pourquoi tu aimes baiser un melon", pctA: 68 },
  { id: 479, a: "devoir expliquer à ta mère pourquoi tu aimes te masturber avec des fruits pourris", b: "transpirer du fromage de bite", pctA: 52 },
  { id: 480, a: "te laver le visage avec du liquide amniotique", b: "avoir des sécrétions qui sentent du fromage de bite", pctA: 26 },
  { id: 481, a: "te laver le visage avec des croûtes de plaies infectées", b: "devoir crier à chaque orgasme : regarder du porno impliquant des nains unijambistes", pctA: 94 },
  { id: 482, a: "remplacer ton shampoing par des croûtes de plaies infectées", b: "avoir un cactus en feu coincé(e) dans l'urètre", pctA: 40 },
  { id: 483, a: "dormir dans des draps imbibés de du jus de poubelle", b: "devoir porter un t-shirt au mariage de ta sœur disant : te lécher le trou du cul", pctA: 19 },
  { id: 484, a: "devoir sucer ta propre grand-mère", b: "devoir te masturber en regardant un prêtre en pleine messe", pctA: 95 },
  { id: 485, a: "découvrir des excréments d'oiseau dans ton slip chaque matin", b: "dormir dans des draps imbibés de des glaires de fumeur", pctA: 54 },
  { id: 486, a: "te faire sodomiser par un prêtre en pleine messe", b: "devoir glisser un cactus en feu sous tes ongles", pctA: 22 },
  { id: 487, a: "te brosser les dents avec du sperme de cheval", b: "éternuer du liquide amniotique", pctA: 48 },
  { id: 488, a: "prendre un bain rempli de de la diarrhée de chien", b: "devoir marcher pieds nus sur des lames de rasoir rouillées", pctA: 58 },
  { id: 489, a: "éternuer de la bave de crapaud", b: "devoir sucer une fosse septique qui déborde", pctA: 28 },
  { id: 490, a: "remplacer ton shampoing par du cérumen noir", b: "saigner du vomi de bébé au lieu de sang", pctA: 44 },
  { id: 491, a: "te faire surprendre par ton patron en train de baiser un melon", b: "dormir dans des draps imbibés de de la diarrhée de chien", pctA: 23 },
  { id: 492, a: "faire un gargarisme avec du liquide amniotique", b: "laisser accidentellement un message vocal à ton ex en plein renifler des culottes sales", pctA: 73 },
  { id: 493, a: "faire un gargarisme avec des rognures d'ongles de pieds", b: "devoir glisser des lames de rasoir rouillées sous tes ongles", pctA: 24 },
  { id: 494, a: "dormir dans des draps imbibés de des croûtes de plaies infectées", b: "pleurer de la pisse d'asthmatique quand tu es triste", pctA: 48 },
  { id: 495, a: "découvrir de la morve verte épaisse dans ton slip chaque matin", b: "remplacer ton shampoing par de la diarrhée de chien", pctA: 17 },
  { id: 496, a: "faire un gargarisme avec de la bave de crapaud", b: "que ton historique de navigation montre que tu cherches souvent comment te doigter dans les toilettes du bureau", pctA: 16 },
  { id: 497, a: "avoir un orgasme chaque fois que tu entends une sirène d'ambulance", b: "transpirer des rognures d'ongles de pieds", pctA: 63 },
  { id: 498, a: "découvrir du sang menstruel caillé dans ton slip chaque matin", b: "devoir porter un t-shirt au mariage de ta sœur disant : renifler des culottes sales", pctA: 57 },
  { id: 499, a: "saigner du jus de poubelle au lieu de sang", b: "avoir des sécrétions qui sentent des excréments d'oiseau", pctA: 93 },
  { id: 500, a: "devoir porter un t-shirt au mariage de ta sœur disant : te frotter les parties génitales sur la poignée de porte", b: "avoir des lames de rasoir rouillées coincé(e) dans l'urètre", pctA: 57 }
];
